server:
  port: 8764
spring:
  application:
    name: article-service
  zipkin:
    base-url: http://localhost:8762
  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true

logging:
  level:
    com.hu.zan: info
